version: "3.7"

services:
  club_app: &app
    image: "ghcr.io/antoniokichaev/club:${GITHUB_SHA:-latest}"
    command: make docker-run-dev
    container_name: club_app
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - .:/app:delegated # enable hot code reload in debug mode
    depends_on:
      - postgres
      - redis
      - queue
      - webpack
    ports:
      - "8000:8000"

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    networks:
      - club_network
    ports: [ ]

  postgres:
    image: postgres:14
    container_name: club_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vas3k_club

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  webpack:
    image: node:14-slim
    command: npm run watch
    restart: always
    volumes:
      - .:/app:delegated
    working_dir: /app/frontend

# Uncomment these lines if you want to test the Club bot locally
#  bot:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    command: make docker-run-bot
#    environment:
#      - MODE=dev
#      - DEBUG=true
#      - PYTHONUNBUFFERED=1
#      - POSTGRES_DB=vas3k_club
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=postgres
#      - REDIS_DB=0
#      - REDIS_HOST=redis
#    restart: always
#    volumes:
#      - .:/app:delegated
#    depends_on:
#      - club_app
#      - postgres
#      - redis

# Uncomment these lines if you want to test the Helpdeskbot locally
#  helpdeskbot:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    command: make docker-run-helpdeskbot
#    environment:
#      - MODE=dev
#      - DEBUG=true
#      - PYTHONUNBUFFERED=1
#      - POSTGRES_DB=vas3k_club
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=postgres
#      - REDIS_DB=0
#      - REDIS_HOST=redis
#    restart: always
#    volumes:
#      - .:/app:delegated
#    depends_on:
#      - club_app
#      - postgres
#      - redis
