name: Deploy production

env:
  REGISTRY: ghcr.io
  ACTOR: antoniokichaev/club

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_TOKEN_CR }}
      - run: docker build -t ghcr.io/${{ env.ACTOR }}:latest -t ghcr.io/${{ env.ACTOR }}:${{ github.sha }} .
      - run: docker image push ghcr.io/${{ env.ACTOR }}:${{ github.sha }}
      - run: docker image push ghcr.io/${{ env.ACTOR }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          script_stop: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ vars.PROJECT_DIR }}
            git pull
            echo ${{ secrets.GH_TOKEN_CR }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            /usr/bin/docker compose --file docker-compose.prod.yaml up -d

    permissions:
      contents: read
      packages: write
